/*
 * minimoni - zero-dependency system monitoring
 * Copyright (C) 2026 Javier Beaumont <javierbeaumont@users.noreply.github.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

/* Integration tests: our X.509 policy against the REAL br_x509_minimal engine, in process, with a
 * real certificate and no sockets. Run with: make test-integration.
 *
 * What this pins is an assumption about a vendored dependency that its docs do not promise: that an
 * unanchored, well-formed chain is reported as BR_ERR_X509_NOT_TRUSTED, and that get_pkey still
 * yields the key in that state. The whole https webhook path rests on it. When BearSSL is bumped, a
 * break here names the cause, where tests/e2e-webhook.sh would only report a lost delivery.
 *
 * Both certificates are generated by the Makefile, not committed: a stored valid one would expire
 * and silently turn into the expired case. */

#include "runner.h"

/* Seams for what alerts.c calls besides BearSSL; src/json.c would pull units.c and config.c, and
 * config.c pulls vendor/tomlc17.c. BearSSL itself is REAL. */
#include "alerts.h"

int json_escape(char *dst, size_t cap, const char *src)
{
    (void)src;
    if (cap)
        dst[0] = '\0';
    return 0;
}
int db_alert_on_cooldown(db_t *db, const char *alert_name, long cooldown_seconds)
{
    (void)db;
    (void)alert_name;
    (void)cooldown_seconds;
    return 1;
}
int db_alert_log_fire(db_t *db, const char *alert_name)
{
    (void)db;
    (void)alert_name;
    return 0;
}

#include "../src/alerts.c"

typedef struct {
    const char   *path;
    unsigned char der[8192];
    size_t        len;
} fixture_t;

static fixture_t g_valid = {.path = "build/x509-selfsigned.der"};
static fixture_t g_expired = {.path = "build/x509-expired.der"};

/* `policy` selects our insecure overrides over the stock vtable. */
static unsigned run_chain(br_x509_minimal_context *xc, int policy, const fixture_t *cert)
{
    static br_x509_class vt;
    vt = br_x509_minimal_vtable;
    if (policy) {
        vt.start_chain = xi_start_chain;
        vt.end_chain = xi_end_chain;
    }

    br_x509_minimal_init_full(xc, NULL, 0);
    xc->vtable = &vt;
    xc->vtable->start_chain(&xc->vtable, "minimoni.test");
    xc->vtable->start_cert(&xc->vtable, (uint32_t)cert->len);
    xc->vtable->append(&xc->vtable, cert->der, cert->len);
    xc->vtable->end_cert(&xc->vtable);
    return xc->vtable->end_chain(&xc->vtable);
}

/* The vendored behaviour the fix depends on. */
static int test_engine_reports_not_trusted(void)
{
    br_x509_minimal_context xc;
    return run_chain(&xc, 0, &g_valid) == BR_ERR_X509_NOT_TRUSTED ? 0 : 1;
}

static int test_policy_accepts_the_chain(void)
{
    br_x509_minimal_context xc;
    return run_chain(&xc, 1, &g_valid) == 0 ? 0 : 1;
}

/* Without a key the handshake dies even though the verdict was dropped, which is exactly how the
 * no-op vtable failed before. */
static int test_key_is_available_after_the_drop(void)
{
    br_x509_minimal_context xc;
    unsigned                usages = 0;
    if (run_chain(&xc, 1, &g_valid) != 0)
        return 1;
    const br_x509_pkey *pk = xc.vtable->get_pkey(&xc.vtable, &usages);
    return pk != NULL && usages != 0 ? 0 : 1;
}

/* The opt-out overrides trust, not validity: an expired chain keeps its verdict. */
static int test_engine_reports_expired(void)
{
    br_x509_minimal_context xc;
    return run_chain(&xc, 0, &g_expired) == BR_ERR_X509_EXPIRED ? 0 : 1;
}

static int test_policy_propagates_expired(void)
{
    br_x509_minimal_context xc;
    return run_chain(&xc, 1, &g_expired) == BR_ERR_X509_EXPIRED ? 0 : 1;
}

/* --- Runner --- */

static const test_t ALL_TESTS[] = {
    T(engine_reports_not_trusted), T(policy_accepts_the_chain),  T(key_is_available_after_the_drop),
    T(engine_reports_expired),     T(policy_propagates_expired),
};

static int load(fixture_t *cert)
{
    FILE *f = fopen(cert->path, "rb");
    if (!f) {
        fprintf(stderr, "  cannot open %s; the Makefile generates it\n", cert->path);
        return -1;
    }
    cert->len = fread(cert->der, 1, sizeof(cert->der), f);
    fclose(f);
    if (cert->len == 0 || cert->len == sizeof(cert->der)) {
        fprintf(stderr, "  %s is empty or larger than the buffer\n", cert->path);
        return -1;
    }
    return 0;
}

int main(void)
{
    if (load(&g_valid) != 0 || load(&g_expired) != 0)
        return 2;
    return run_tests(ALL_TESTS, sizeof(ALL_TESTS) / sizeof(ALL_TESTS[0]));
}
